function derivare(E,T,f,N,R,C,tau,D,E0)
Fig=figure('Name','Circuit de derivare cu RC',... 
 'Units','normalized',...
 'Color','#EBF4FA',...
 'Position',[.2 .1 .75 .8],...
 'NumberTitle','off');

T=1/f;
t=0:T/100:N*T;
Vi= E*sign(sin(2*pi*f.*t));

Vi=E0+(E*sign(sin(2*pi*f.*t)));

Btitle=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.3 0.92 0.45 0.07],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',20,...
 'String','Circuit de derivare cu RC');

img=imread('Circuit.jpg');
subplot('Position',[0.02 0.65 0.28 0.28]);
 imshow(img);

 %parametrii circuitului

 Group1=uibuttongroup('Visible','on',...
 'BackgroundColor','#EBF4FA',...
'ForegroundColor','black',...
 'Title','Parametrii circuitului',...
 'FontSize',12,...
'TitlePosition','centertop',...
 'Tag','text',...
 'Position',[0.35 0.73 0.15 0.15]);

%rezistenta
Bt_R=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.56 0.40 0.4],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',14,...
 'String','R [Ω]',...
 'Parent',Group1);

Bt_Re=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.51 0.56 0.35 0.4],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String',R,...
 'Callback','R=str2num(get(gco,''String''));close;derivare(E,T,f,N,R,C,tau,D,E0)',...
 'Parent',Group1);

%condensatorul
Bt_C=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.12 0.40 0.4],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',14,...
 'String','C [F]',...
 'Parent',Group1);

Bt_Ce=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.51 0.12 0.35 0.4],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String',C,...
 'Callback','C=str2num(get(gco,''String''));close;derivare(E,T,f,N,R,C,tau,D,E0)',...
 'Parent',Group1);


if (C==0)
    close;
    msgbox('Condensatorul nu poate fi 0!');
end


tau=R*C;

%semnal de intrare
Group2=uibuttongroup('Visible','on',...
 'BackgroundColor','#EBF4FA',...
'ForegroundColor','black',...
 'Title','Semnal de intrare',...
 'FontSize',12,...
'TitlePosition','centertop',...
 'Tag','text',...
 'Position',[0.77 0.57 0.18 0.4]);

%componenta continua 
Bt_E0=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.85 0.25 0.1],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','E0 [V]',...
 'Parent',Group2);

Bt_E0e=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.85 0.27 0.1],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'Parent',Group2,...
 'String',E0,...
 'Callback','E0=str2num(get(gco,''String''));close;derivare(E,T,f,N,R,C,tau,D,E0)');



%tensiunea
Bt_E=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.73 0.25 0.1],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','E [V]',...
 'Parent',Group2);

Bt_Ee=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.73 0.27 0.1],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'Parent',Group2,...
 'String',E,...
 'Callback','E=str2num(get(gco,''String''));close;derivare(E,T,f,N,R,C,tau,D,E0)');


%frecventa
Bt_f=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.58 0.25 0.1],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','f [Hz]',...
 'Parent',Group2);

Bt_fe=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.58 0.27 0.1],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String',f,...
 'Callback','f=str2num(get(gco,''String''));close;derivare(E,T,f,N,R,C,tau,D,E0)',...
 'Parent',Group2);

%conditie

if (f==0)
    close;
    msgbox('Frecventa nu poate fi 0!');
end

% Vi= E*sign(sin(2*pi*f.*t));
% 
% Vi=E0+(E*sign(sin(2*pi*f.*t)));

%perioada

Bt_T=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.38 0.25 0.1],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','T [s]',...
 'Parent',Group2);

Bt_Te=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.38 0.27 0.1],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String',T,...
 'Enable','off',...
 'Callback','T=str2num(get(gco,''String''));close;derivare(E,T,f,N,R,C,tau,D,E0)',...
 'Parent',Group2);

%numarul de perioade
Bt_N=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.15 0.35 0.15],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',12,...
 'String','Număr perioade',...
 'Parent',Group2);

Bt_Ne=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.18 0.27 0.1],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String',N,...
 'Callback','N=str2num(get(gco,''String''));close;derivare(E,T,f,N,R,C,tau,D,E0)',...
 'Parent',Group2);

%constanta de timp
Bt_tau=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.55 0.8 0.08 0.05],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','τ [s]');

Bt_taue=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.63 0.8 0.08 0.05],...
 'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String',tau,...
 'Callback','tau=str2num(get(gco,''String''));close;derivare(E,T,f,N,R,C,tau,D,E0)');


%grafic Tensiuni
subplot('Position',[0.08 0.1 0.4 0.35]);
plot(t,Vi,'-k','LineWidth',2);
grid on;
hold on;
title('Tensiuni');
xlabel('timp [s]');
ylabel('amplitudine [V]')
% ylim([(-2*E)-2 2*E+2]);


%buton close
Bp=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.05 0.55 0.16 0.05],...
'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',12,...
'String','Close',...
'Callback','close');

%buton reset
Bp=uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.22 0.55 0.16 0.05],...
'backgroundcolor','#EBF4FA',...
 'foregroundcolor','black',...
 'FontSize',12,...
'String','Reset',...
'Callback','Reset=str2num(get(gco,''String''));close;derivare(5,1/f,1000,5,10*10^3,10*10^(-9),R*C,0.5,0)');

Tc=D.*T;
y=0; %conditiile initiale, 
for j=1:N
d(j)=min(y); %conditiile initiale,
[t,y]=ode45('F1',[(j-1).*T (j-1).*T+Tc],[d(j)],[],E,R,C); 
a(j)=max(y); %conditiile initiale,
subplot('Position',[0.55 0.1 0.4 0.35]);
plot(t,y,'r');hold on;grid on;
[t,y]=ode45('F2',[(j-1).*T+Tc j.*T],[a(j)],[],E,R,C);
plot(t,y,'b');
title('Tensiunea pe condensator');
hold on; 
subplot('Position',[0.55 0.1 0.4 0.35]); ylabel('Vc[V]');
xlabel('timp [s]'); 
end


%tensiune rezistenta-tensiunea de iesire
for j=1:N
d(j)=min(y); %conditiile initiale,
[t,y]=ode45('F1',[(j-1).*T (j-1).*T+Tc],[d(j)],[],E,R,C); 
z=E-y;
a(j)=max(y); %conditiile initiale,
subplot('Position',[0.08 0.1 0.4 0.35]);
plot(t,z,'b','LineWidth',2);hold on;grid on;
[t,y]=ode45('F2',[(j-1).*T+Tc j.*T],[a(j)],[],E,R,C);
zz=-y;
plot(t,zz,'r','LineWidth',2);hold on; 
subplot('Position',[0.08 0.1 0.4 0.35]);
ylabel('Vo/Vi[V]');
xlabel('timp [s]'); 
end

% line([T/2 T/2], [-2*E 0],'Color','b','LineWidth',2);
% line([T T], [0 2*E],'Color','r','LineWidth',2);

%curentul prin circuit
for j=1:N
d(j)=min(y); %conditiile initiale,
[t,y]=ode45('F1',[(j-1).*T (j-1).*T+Tc],[d(j)],[],E,R,C); 
i=(E-y)./R;
a(j)=max(y); %conditiile initiale,
subplot('Position',[0.54 0.56 0.20 0.20]);
plot(t,i,'r');hold on;grid on;
[t,y]=ode45('F2',[(j-1).*T+Tc j.*T],[a(j)],[],E,R,C);
i=(-y)./R;
plot(t,i,'b');
title('Curentul');
hold on; 
subplot('Position',[0.54 0.56 0.20 0.20]); ylabel('I[A]');
xlabel('timp [s]'); 
end

%conditii componente

if (T<0 || f<0 || N<0 || E<0 || R<0 || C<0)
    close;
   msgbox('Această componentă nu poate fi negativă! Introduceți o nouă valoare!');
end


if (T==0 || N==0 || E==0 || R==0 || C==0)
    close;
   msgbox('Această componentă nu poate fi 0!');
end


f=uimenu('Label','Documentație');
uimenu(f,'Label','Titlul proiectului','Callback','open(''titlu_proiect.htm'')');
uimenu(f,'Label','Descriere proiect','Callback','open(''Descriere_proiect.htm'')');
uimenu(f,'Label','Functionare','Callback','open(''Functionare.htm'')');
uimenu(f,'Label','Ecuații proiect','Callback','open(''Ecuatii_proiect.htm'')');
uimenu(f,'Label','Utilizare interfață','Callback','open(''utilizare_interfata.htm'')');
uimenu(f,'Label','Bibliografie','Callback','open(''Bibliografie.htm'')');


end
